version: '3.8'

services:
  proxy:
    container_name: frontend-proxy
    image: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - $PWD/docker/proxy.conf.template:/etc/nginx/templates/proxy.conf.template
      # - $PWD/certs:/etc/nginx/certs
    env_file:
      - .env-docker
